/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Jhesi Colque
 */
public class v2 extends javax.swing.JFrame {
   private v1 v1;
    private ArchivoComprador archiComprador = new ArchivoComprador();
    private String autor,correo,tipo,monto,detalle;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(v2.class.getName());
    
    /**
     * Creates new form subastaa
     */
    public v2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_Registrarse = new javax.swing.JButton();
        BTN_OBRAS = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        PESTAÑAS = new javax.swing.JTabbedPane();
        PNL_OBRAS = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AUTOR_OBRA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TIPO_PAGO = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        CORREO_OBRA = new javax.swing.JTextField();
        BTN_AgregarPuja = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TABLA_COMP = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        TABLA_REGISTROS = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        MONTO_OBRA = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        DETALLES_OBRA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(370, 110));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(25, 50, 90));

        btn_Registrarse.setBackground(new java.awt.Color(41, 74, 124));
        btn_Registrarse.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btn_Registrarse.setForeground(new java.awt.Color(204, 204, 255));
        btn_Registrarse.setText("Regresar");
        btn_Registrarse.setActionCommand("");
        btn_Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarseActionPerformed(evt);
            }
        });

        BTN_OBRAS.setBackground(new java.awt.Color(85, 119, 173));
        BTN_OBRAS.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BTN_OBRAS.setForeground(new java.awt.Color(204, 204, 255));
        BTN_OBRAS.setText("Registro para \npujas");
        BTN_OBRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_OBRASActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/LOGO_CHIQUITO.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTN_OBRAS, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btn_Registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_Registrarse)
                .addGap(35, 35, 35)
                .addComponent(BTN_OBRAS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(39, 39, 39))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 400));

        PESTAÑAS.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        PNL_OBRAS.setBackground(new java.awt.Color(70, 130, 180));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Autor:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("C O M P R A D O R");

        AUTOR_OBRA.setBackground(new java.awt.Color(153, 204, 255));
        AUTOR_OBRA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AUTOR_OBRA.setForeground(new java.awt.Color(51, 51, 51));
        AUTOR_OBRA.setActionCommand("<Not Set>");
        AUTOR_OBRA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 108, 205)));
        AUTOR_OBRA.setName(""); // NOI18N
        AUTOR_OBRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AUTOR_OBRAActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo de Pago:");

        TIPO_PAGO.setBackground(new java.awt.Color(153, 204, 255));
        TIPO_PAGO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TIPO_PAGO.setForeground(new java.awt.Color(51, 51, 51));
        TIPO_PAGO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta de crédito", "Efectivo", "Tarjeta de débito", "Transferencia bancaria", "Pago móvil" }));
        TIPO_PAGO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 108, 205)));
        TIPO_PAGO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TIPO_PAGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIPO_PAGOActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Correo:");

        CORREO_OBRA.setBackground(new java.awt.Color(153, 204, 255));
        CORREO_OBRA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CORREO_OBRA.setForeground(new java.awt.Color(51, 51, 51));
        CORREO_OBRA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 108, 205)));
        CORREO_OBRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CORREO_OBRAActionPerformed(evt);
            }
        });

        BTN_AgregarPuja.setBackground(new java.awt.Color(0, 102, 102));
        BTN_AgregarPuja.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        BTN_AgregarPuja.setForeground(new java.awt.Color(204, 204, 255));
        BTN_AgregarPuja.setText("Pujar");
        BTN_AgregarPuja.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 51, 51)));
        BTN_AgregarPuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AgregarPujaActionPerformed(evt);
            }
        });

        TABLA_COMP.setBackground(new java.awt.Color(0, 204, 204));
        TABLA_COMP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Paterno", "Materno", "Tipo de Pago", "Adjudicacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TABLA_COMP);

        TABLA_REGISTROS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Autor", "Precio base", "Estado", "Tipo Obra"
            }
        ));
        TABLA_REGISTROS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLA_REGISTROSMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TABLA_REGISTROS);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Monto A Pujar:");

        MONTO_OBRA.setBackground(new java.awt.Color(153, 204, 255));
        MONTO_OBRA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MONTO_OBRA.setForeground(new java.awt.Color(51, 51, 51));
        MONTO_OBRA.setActionCommand("<Not Set>");
        MONTO_OBRA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 108, 205)));
        MONTO_OBRA.setName(""); // NOI18N
        MONTO_OBRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MONTO_OBRAActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Detalles");

        DETALLES_OBRA.setBackground(new java.awt.Color(153, 204, 255));
        DETALLES_OBRA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DETALLES_OBRA.setForeground(new java.awt.Color(51, 51, 51));
        DETALLES_OBRA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 108, 205)));
        DETALLES_OBRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DETALLES_OBRAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNL_OBRASLayout = new javax.swing.GroupLayout(PNL_OBRAS);
        PNL_OBRAS.setLayout(PNL_OBRASLayout);
        PNL_OBRASLayout.setHorizontalGroup(
            PNL_OBRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_OBRASLayout.createSequentialGroup()
                .addGroup(PNL_OBRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_OBRASLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PNL_OBRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_OBRASLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(AUTOR_OBRA, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel7)
                                .addGap(26, 26, 26)
                                .addComponent(CORREO_OBRA, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(PNL_OBRASLayout.createSequentialGroup()
                                .addGroup(PNL_OBRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PNL_OBRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TIPO_PAGO, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PNL_OBRASLayout.createSequentialGroup()
                                        .addComponent(MONTO_OBRA, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DETALLES_OBRA))))
                            .addComponent(BTN_AgregarPuja, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PNL_OBRASLayout.createSequentialGroup()
                        .addGap(465, 465, 465)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNL_OBRASLayout.setVerticalGroup(
            PNL_OBRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_OBRASLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNL_OBRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AUTOR_OBRA)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CORREO_OBRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PNL_OBRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TIPO_PAGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNL_OBRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MONTO_OBRA)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DETALLES_OBRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTN_AgregarPuja, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(401, 401, 401))
        );

        PESTAÑAS.addTab("tab1", PNL_OBRAS);

        getContentPane().add(PESTAÑAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 0, 530, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setV1(v1 v1){
        this.v1 = v1;
    }
    private void btn_RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarseActionPerformed

        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_RegistrarseActionPerformed

    private void BTN_OBRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_OBRASActionPerformed
        // TODO add your handling code here:
        PESTAÑAS.setSelectedIndex(0);
        try {
        // Limpiar la tabla
        
        DefaultTableModel modelo = (DefaultTableModel) TABLA_REGISTROS.getModel();
        modelo.setRowCount(0);
        
        // Leer archivo y llenar tabla
        ObjectInputStream arch = new ObjectInputStream(new FileInputStream("archivoObras.dat"));
        
        while (true) {
            Obra c = (Obra) arch.readObject();
            Object[] fila = {c.getCorreo(), c.getAutor(), c.getPrecioBase(), c.getEstadoCompra(),c.getDetalle()};
            modelo.addRow(fila);
        }
        
        } catch (EOFException e) {
            // Normal - fin del archivo
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }        
    }//GEN-LAST:event_BTN_OBRASActionPerformed

    private void BTN_AgregarPujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AgregarPujaActionPerformed
                                              
    try {
        // Obtener datos del formulario
        String correoObra = CORREO_OBRA.getText().trim();
        String tipoPago = TIPO_PAGO.getSelectedItem().toString();
        String monto = MONTO_OBRA.getText().trim();
        
        // Validar campos
        if (correoObra.isEmpty() || monto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Correo de obra y monto son obligatorios", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validar que el monto sea numérico
        try {
            double montoNumerico = Double.parseDouble(monto);
            if (montoNumerico <= 0) {
                JOptionPane.showMessageDialog(this, "El monto debe ser mayor a cero", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El monto debe ser un número válido", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Obtener datos del comprador (del login)
        String nombreComprador = v1.nom;
        String apellidoComprador = v1.pat;
        String correoComprador = v1.correo;
        
        // Crear objeto Puja
        Puja nuevaPuja = new Puja(tipoPago, monto, nombreComprador, apellidoComprador, correoComprador);
        
        // Agregar puja al sistema
        ArchObras archObras = new ArchObras();
        ArchPujas archPujas = new ArchPujas(archObras);
        
        // Verificar que la obra existe antes de agregar la puja
        boolean[] obraExiste = {false};
        archObras.buscarObra(correoObra, obra -> obraExiste[0] = true);
        
        if (!obraExiste[0]) {
            JOptionPane.showMessageDialog(this, "La obra con este correo no existe", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Agregar la puja
        archPujas.agregarPuja(correoObra, nuevaPuja);
        
        // Mostrar confirmación
        JOptionPane.showMessageDialog(this, "Puja registrada exitosamente", 
            "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        // Limpiar campos después de agregar
        MONTO_OBRA.setText("");
        
    } catch (IOException | ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(this, "Error al registrar la puja: " + ex.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error inesperado: " + ex.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
        
    }//GEN-LAST:event_BTN_AgregarPujaActionPerformed

    private void CORREO_OBRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CORREO_OBRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CORREO_OBRAActionPerformed

    private void TIPO_PAGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIPO_PAGOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIPO_PAGOActionPerformed

    private void AUTOR_OBRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AUTOR_OBRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AUTOR_OBRAActionPerformed

    private void TABLA_REGISTROSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLA_REGISTROSMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_TABLA_REGISTROSMouseClicked

    private void MONTO_OBRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MONTO_OBRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MONTO_OBRAActionPerformed

    private void DETALLES_OBRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DETALLES_OBRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DETALLES_OBRAActionPerformed
    
    /**
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new v2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AUTOR_OBRA;
    private javax.swing.JToggleButton BTN_AgregarPuja;
    private javax.swing.JToggleButton BTN_OBRAS;
    private javax.swing.JTextField CORREO_OBRA;
    private javax.swing.JTextField DETALLES_OBRA;
    private javax.swing.JTextField MONTO_OBRA;
    private javax.swing.JTabbedPane PESTAÑAS;
    private javax.swing.JPanel PNL_OBRAS;
    private javax.swing.JTable TABLA_COMP;
    private javax.swing.JTable TABLA_REGISTROS;
    private javax.swing.JComboBox<String> TIPO_PAGO;
    private javax.swing.JButton btn_Registrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
