/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import java.io.IOException;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhesi Colque
 */
public class v3 extends javax.swing.JFrame {
    private String correo,autor,estado,tecnica,detallesObra,precioTexto,material,materialE;
    private int preciobase,dimension,peso,precio;
    private String tipoLapiz,tipoPapel;
    private v1 v1;
    private ArchObras archiObra = new ArchObras();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(v3.class.getName());

    /**
     * Creates new form v3
     */
    public v3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Regresar = new javax.swing.JButton();
        BTN_REGISTRAR = new javax.swing.JButton();
        BTN_AGREGAR = new javax.swing.JButton();
        BTN_BUSCAR_EXPOSITOR = new javax.swing.JButton();
        BTN_BUSCAR_POR_TIP = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pestañas = new javax.swing.JTabbedPane();
        PNL_REGISTRAR = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_REGISTROS = new javax.swing.JTable();
        PNL_AGREGAR = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Menu_Obras = new javax.swing.JTabbedPane();
        PNL_PINTURA = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        INGRESO_DIMPINTURA = new javax.swing.JTextField();
        INGRESO_TECNICAPIN = new javax.swing.JTextField();
        BTN_AGREGARPINTURA = new javax.swing.JToggleButton();
        PNL_ESCULTURA = new javax.swing.JPanel();
        INGRESO_MATERIAL = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        INGRESO_PESO = new javax.swing.JTextField();
        BTNAGREGAR_ESCULTURA = new javax.swing.JButton();
        PNL_DIBUJO = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        INGRESO_TIPPAPEL = new javax.swing.JTextField();
        INGRESO_TIPLAPIZ = new javax.swing.JTextField();
        BTNAGREGAR_DIBUJO = new javax.swing.JButton();
        PNL_CERAMICA = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        AGREGAR_TIPOCERAMICA = new javax.swing.JTextField();
        AGREGAR_MATERIALCERAMICA = new javax.swing.JTextField();
        BTN_AGREGARCERAMICA = new javax.swing.JButton();
        TIPOOBRA = new javax.swing.JComboBox<>();
        INGRESO_PRECIOBASE = new javax.swing.JTextField();
        INGRESO_AUTOR = new javax.swing.JTextField();
        BTN_SELECCIONAR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        INGRESO_ESTADO = new javax.swing.JTextField();
        PNL_BUSCAR = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLA_BUSCAR = new javax.swing.JTable();
        CORREO_EXPOSITOR = new javax.swing.JTextField();
        BTN_BUSCAR_EXP = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        PNL_BUSCAR_TIPO = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TABLA_BUSCAR_POR_TIPO = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TIPO_OBRA = new javax.swing.JComboBox<>();
        BTN_BUSCAR_POR_TIPO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 140));
        setPreferredSize(new java.awt.Dimension(760, 490));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(64, 64, 64));

        btn_Regresar.setBackground(new java.awt.Color(224, 224, 224));
        btn_Regresar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btn_Regresar.setText("Regresar");
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });

        BTN_REGISTRAR.setBackground(new java.awt.Color(200, 200, 200));
        BTN_REGISTRAR.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BTN_REGISTRAR.setForeground(new java.awt.Color(102, 102, 102));
        BTN_REGISTRAR.setText("Verificar Registro");
        BTN_REGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_REGISTRARActionPerformed(evt);
            }
        });

        BTN_AGREGAR.setBackground(new java.awt.Color(200, 200, 200));
        BTN_AGREGAR.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BTN_AGREGAR.setForeground(new java.awt.Color(102, 102, 102));
        BTN_AGREGAR.setText("Agregar Obra");
        BTN_AGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AGREGARActionPerformed(evt);
            }
        });

        BTN_BUSCAR_EXPOSITOR.setBackground(new java.awt.Color(200, 200, 200));
        BTN_BUSCAR_EXPOSITOR.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BTN_BUSCAR_EXPOSITOR.setForeground(new java.awt.Color(102, 102, 102));
        BTN_BUSCAR_EXPOSITOR.setText("Buscar Expositor");
        BTN_BUSCAR_EXPOSITOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BUSCAR_EXPOSITORActionPerformed(evt);
            }
        });

        BTN_BUSCAR_POR_TIP.setBackground(new java.awt.Color(200, 200, 200));
        BTN_BUSCAR_POR_TIP.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BTN_BUSCAR_POR_TIP.setForeground(new java.awt.Color(102, 102, 102));
        BTN_BUSCAR_POR_TIP.setText("Buscar Tipo Obra");
        BTN_BUSCAR_POR_TIP.setToolTipText("");
        BTN_BUSCAR_POR_TIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BUSCAR_POR_TIPActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/LOGO_CHIQUITO.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_REGISTRAR, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(BTN_AGREGAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_BUSCAR_EXPOSITOR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_BUSCAR_POR_TIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel5)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btn_Regresar)
                .addGap(37, 37, 37)
                .addComponent(BTN_REGISTRAR)
                .addGap(18, 18, 18)
                .addComponent(BTN_AGREGAR)
                .addGap(18, 18, 18)
                .addComponent(BTN_BUSCAR_EXPOSITOR)
                .addGap(18, 18, 18)
                .addComponent(BTN_BUSCAR_POR_TIP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pestañas.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        PNL_REGISTRAR.setBackground(new java.awt.Color(128, 128, 128));
        PNL_REGISTRAR.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Verificar Obra Registrada");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Mis registros:");

        TABLA_REGISTROS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Autor", "Precio base", "Estado", "Tipo Obra"
            }
        ));
        jScrollPane1.setViewportView(TABLA_REGISTROS);

        javax.swing.GroupLayout PNL_REGISTRARLayout = new javax.swing.GroupLayout(PNL_REGISTRAR);
        PNL_REGISTRAR.setLayout(PNL_REGISTRARLayout);
        PNL_REGISTRARLayout.setHorizontalGroup(
            PNL_REGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_REGISTRARLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(PNL_REGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_REGISTRARLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(122, 122, 122))
        );
        PNL_REGISTRARLayout.setVerticalGroup(
            PNL_REGISTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_REGISTRARLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pestañas.addTab("tab2", PNL_REGISTRAR);

        PNL_AGREGAR.setBackground(new java.awt.Color(128, 128, 128));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Agregar Obra");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Autor:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio Base:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de obra:");

        Menu_Obras.setBackground(new java.awt.Color(102, 102, 102));
        Menu_Obras.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        PNL_PINTURA.setBackground(new java.awt.Color(102, 102, 102));
        PNL_PINTURA.setPreferredSize(new java.awt.Dimension(472, 200));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pintura");

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Dimension:");

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Tecnica: ");

        BTN_AGREGARPINTURA.setBackground(new java.awt.Color(51, 51, 51));
        BTN_AGREGARPINTURA.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BTN_AGREGARPINTURA.setForeground(new java.awt.Color(255, 255, 255));
        BTN_AGREGARPINTURA.setText("Agregar");
        BTN_AGREGARPINTURA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AGREGARPINTURAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNL_PINTURALayout = new javax.swing.GroupLayout(PNL_PINTURA);
        PNL_PINTURA.setLayout(PNL_PINTURALayout);
        PNL_PINTURALayout.setHorizontalGroup(
            PNL_PINTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_PINTURALayout.createSequentialGroup()
                .addGroup(PNL_PINTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_PINTURALayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PNL_PINTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(29, 29, 29)
                        .addGroup(PNL_PINTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(INGRESO_TECNICAPIN, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(INGRESO_DIMPINTURA)))
                    .addGroup(PNL_PINTURALayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(PNL_PINTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_AGREGARPINTURA)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(150, 150, 150))
        );
        PNL_PINTURALayout.setVerticalGroup(
            PNL_PINTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_PINTURALayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(PNL_PINTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(INGRESO_DIMPINTURA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PNL_PINTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(INGRESO_TECNICAPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTN_AGREGARPINTURA)
                .addContainerGap())
        );

        Menu_Obras.addTab("      ", PNL_PINTURA);

        PNL_ESCULTURA.setBackground(new java.awt.Color(102, 102, 102));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Escultura");

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Material: ");

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Peso:");

        BTNAGREGAR_ESCULTURA.setBackground(new java.awt.Color(51, 51, 51));
        BTNAGREGAR_ESCULTURA.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BTNAGREGAR_ESCULTURA.setForeground(new java.awt.Color(204, 204, 204));
        BTNAGREGAR_ESCULTURA.setText("Agregar");
        BTNAGREGAR_ESCULTURA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAGREGAR_ESCULTURAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNL_ESCULTURALayout = new javax.swing.GroupLayout(PNL_ESCULTURA);
        PNL_ESCULTURA.setLayout(PNL_ESCULTURALayout);
        PNL_ESCULTURALayout.setHorizontalGroup(
            PNL_ESCULTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_ESCULTURALayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(PNL_ESCULTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PNL_ESCULTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_ESCULTURALayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(PNL_ESCULTURALayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(PNL_ESCULTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_ESCULTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(INGRESO_MATERIAL, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                .addComponent(INGRESO_PESO))
                            .addComponent(BTNAGREGAR_ESCULTURA))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PNL_ESCULTURALayout.setVerticalGroup(
            PNL_ESCULTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_ESCULTURALayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel12)
                .addGap(16, 16, 16)
                .addGroup(PNL_ESCULTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(INGRESO_MATERIAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PNL_ESCULTURALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(INGRESO_PESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(BTNAGREGAR_ESCULTURA)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        Menu_Obras.addTab("tab4", PNL_ESCULTURA);

        PNL_DIBUJO.setBackground(new java.awt.Color(102, 102, 102));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Dibujo");

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Tipo de papel:");

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Tipo de lapiz:");

        INGRESO_TIPPAPEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESO_TIPPAPELActionPerformed(evt);
            }
        });

        INGRESO_TIPLAPIZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESO_TIPLAPIZActionPerformed(evt);
            }
        });

        BTNAGREGAR_DIBUJO.setBackground(new java.awt.Color(51, 51, 51));
        BTNAGREGAR_DIBUJO.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BTNAGREGAR_DIBUJO.setForeground(new java.awt.Color(204, 204, 204));
        BTNAGREGAR_DIBUJO.setText("Agregar");
        BTNAGREGAR_DIBUJO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAGREGAR_DIBUJOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNL_DIBUJOLayout = new javax.swing.GroupLayout(PNL_DIBUJO);
        PNL_DIBUJO.setLayout(PNL_DIBUJOLayout);
        PNL_DIBUJOLayout.setHorizontalGroup(
            PNL_DIBUJOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_DIBUJOLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(PNL_DIBUJOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(INGRESO_TIPLAPIZ, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNL_DIBUJOLayout.createSequentialGroup()
                        .addGroup(PNL_DIBUJOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addGroup(PNL_DIBUJOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_DIBUJOLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PNL_DIBUJOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTNAGREGAR_DIBUJO)
                                    .addComponent(jLabel15)))
                            .addGroup(PNL_DIBUJOLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(INGRESO_TIPPAPEL, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        PNL_DIBUJOLayout.setVerticalGroup(
            PNL_DIBUJOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_DIBUJOLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNL_DIBUJOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(INGRESO_TIPPAPEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PNL_DIBUJOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(INGRESO_TIPLAPIZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(BTNAGREGAR_DIBUJO)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        Menu_Obras.addTab("tab3", PNL_DIBUJO);

        PNL_CERAMICA.setBackground(new java.awt.Color(102, 102, 102));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Ceramica");

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Tipo:");

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Material:");

        BTN_AGREGARCERAMICA.setBackground(new java.awt.Color(51, 51, 51));
        BTN_AGREGARCERAMICA.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BTN_AGREGARCERAMICA.setForeground(new java.awt.Color(255, 255, 255));
        BTN_AGREGARCERAMICA.setText("Agregar");
        BTN_AGREGARCERAMICA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AGREGARCERAMICAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNL_CERAMICALayout = new javax.swing.GroupLayout(PNL_CERAMICA);
        PNL_CERAMICA.setLayout(PNL_CERAMICALayout);
        PNL_CERAMICALayout.setHorizontalGroup(
            PNL_CERAMICALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_CERAMICALayout.createSequentialGroup()
                .addGroup(PNL_CERAMICALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_CERAMICALayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PNL_CERAMICALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(PNL_CERAMICALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AGREGAR_TIPOCERAMICA, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(AGREGAR_MATERIALCERAMICA)))
                    .addGroup(PNL_CERAMICALayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(PNL_CERAMICALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_AGREGARCERAMICA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        PNL_CERAMICALayout.setVerticalGroup(
            PNL_CERAMICALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_CERAMICALayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNL_CERAMICALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(AGREGAR_TIPOCERAMICA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PNL_CERAMICALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(AGREGAR_MATERIALCERAMICA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTN_AGREGARCERAMICA)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        Menu_Obras.addTab("tab2", PNL_CERAMICA);

        TIPOOBRA.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        TIPOOBRA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione opcion", "Pintura", "Escultura", "Dibujo", "Ceramica" }));

        INGRESO_PRECIOBASE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESO_PRECIOBASEActionPerformed(evt);
            }
        });

        BTN_SELECCIONAR.setBackground(new java.awt.Color(51, 51, 51));
        BTN_SELECCIONAR.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BTN_SELECCIONAR.setForeground(new java.awt.Color(255, 255, 255));
        BTN_SELECCIONAR.setText("Seleccionar");
        BTN_SELECCIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SELECCIONARActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estado:");

        javax.swing.GroupLayout PNL_AGREGARLayout = new javax.swing.GroupLayout(PNL_AGREGAR);
        PNL_AGREGAR.setLayout(PNL_AGREGARLayout);
        PNL_AGREGARLayout.setHorizontalGroup(
            PNL_AGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_AGREGARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(213, 213, 213))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_AGREGARLayout.createSequentialGroup()
                .addGroup(PNL_AGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PNL_AGREGARLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(PNL_AGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_AGREGARLayout.createSequentialGroup()
                                .addGroup(PNL_AGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGroup(PNL_AGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PNL_AGREGARLayout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(INGRESO_ESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_AGREGARLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TIPOOBRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTN_SELECCIONAR, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_AGREGARLayout.createSequentialGroup()
                                .addGroup(PNL_AGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PNL_AGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(INGRESO_PRECIOBASE, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(INGRESO_AUTOR, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PNL_AGREGARLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Menu_Obras, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        PNL_AGREGARLayout.setVerticalGroup(
            PNL_AGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_AGREGARLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(PNL_AGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(INGRESO_AUTOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(PNL_AGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INGRESO_PRECIOBASE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(PNL_AGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INGRESO_ESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addGroup(PNL_AGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TIPOOBRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_SELECCIONAR)
                    .addComponent(jLabel8))
                .addGap(7, 7, 7)
                .addComponent(Menu_Obras, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pestañas.addTab("tab1", PNL_AGREGAR);

        PNL_BUSCAR.setBackground(new java.awt.Color(128, 128, 128));
        PNL_BUSCAR.setForeground(new java.awt.Color(204, 204, 204));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 1, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("BUSCAR OBRAS");

        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Registros de: ");

        TABLA_BUSCAR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Autor", "Precio base", "Estado", "Tipo Obra"
            }
        ));
        jScrollPane2.setViewportView(TABLA_BUSCAR);

        CORREO_EXPOSITOR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CORREO_EXPOSITOR.setToolTipText("");
        CORREO_EXPOSITOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CORREO_EXPOSITORActionPerformed(evt);
            }
        });

        BTN_BUSCAR_EXP.setBackground(new java.awt.Color(51, 51, 51));
        BTN_BUSCAR_EXP.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BTN_BUSCAR_EXP.setForeground(new java.awt.Color(255, 255, 255));
        BTN_BUSCAR_EXP.setText("BUSCAR");
        BTN_BUSCAR_EXP.setPreferredSize(new java.awt.Dimension(81, 26));
        BTN_BUSCAR_EXP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BUSCAR_EXPActionPerformed(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Ingrese correo del expositor");

        javax.swing.GroupLayout PNL_BUSCARLayout = new javax.swing.GroupLayout(PNL_BUSCAR);
        PNL_BUSCAR.setLayout(PNL_BUSCARLayout);
        PNL_BUSCARLayout.setHorizontalGroup(
            PNL_BUSCARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_BUSCARLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PNL_BUSCARLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(PNL_BUSCARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNL_BUSCARLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_BUSCARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(PNL_BUSCARLayout.createSequentialGroup()
                                .addComponent(CORREO_EXPOSITOR, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTN_BUSCAR_EXP, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        PNL_BUSCARLayout.setVerticalGroup(
            PNL_BUSCARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_BUSCARLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNL_BUSCARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(CORREO_EXPOSITOR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_BUSCAR_EXP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pestañas.addTab("tab2", PNL_BUSCAR);

        PNL_BUSCAR_TIPO.setBackground(new java.awt.Color(128, 128, 128));
        PNL_BUSCAR_TIPO.setForeground(new java.awt.Color(204, 204, 204));

        TABLA_BUSCAR_POR_TIPO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Autor", "Precio base", "Estado", "Tipo Obra"
            }
        ));
        jScrollPane3.setViewportView(TABLA_BUSCAR_POR_TIPO);

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 1, 22)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("BUSCAR OBRAS");

        jLabel27.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Tipo de obra:");

        TIPO_OBRA.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        TIPO_OBRA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione opcion", "Pintura", "Escultura", "Dibujo", "Cerámica" }));
        TIPO_OBRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIPO_OBRAActionPerformed(evt);
            }
        });

        BTN_BUSCAR_POR_TIPO.setBackground(new java.awt.Color(51, 51, 51));
        BTN_BUSCAR_POR_TIPO.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BTN_BUSCAR_POR_TIPO.setForeground(new java.awt.Color(255, 255, 255));
        BTN_BUSCAR_POR_TIPO.setText("BUSCAR");
        BTN_BUSCAR_POR_TIPO.setPreferredSize(new java.awt.Dimension(81, 26));
        BTN_BUSCAR_POR_TIPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BUSCAR_POR_TIPOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNL_BUSCAR_TIPOLayout = new javax.swing.GroupLayout(PNL_BUSCAR_TIPO);
        PNL_BUSCAR_TIPO.setLayout(PNL_BUSCAR_TIPOLayout);
        PNL_BUSCAR_TIPOLayout.setHorizontalGroup(
            PNL_BUSCAR_TIPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_BUSCAR_TIPOLayout.createSequentialGroup()
                .addGroup(PNL_BUSCAR_TIPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_BUSCAR_TIPOLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PNL_BUSCAR_TIPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_BUSCAR_TIPOLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TIPO_OBRA, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTN_BUSCAR_POR_TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PNL_BUSCAR_TIPOLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel26)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        PNL_BUSCAR_TIPOLayout.setVerticalGroup(
            PNL_BUSCAR_TIPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_BUSCAR_TIPOLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(PNL_BUSCAR_TIPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TIPO_OBRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(BTN_BUSCAR_POR_TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pestañas.addTab("tab2", PNL_BUSCAR_TIPO);

        getContentPane().add(pestañas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setV1(v1 v1){
        this.v1 = v1;
    }
    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_RegresarActionPerformed

    private void BTN_REGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_REGISTRARActionPerformed
        pestañas.setSelectedIndex(0);
    
    }//GEN-LAST:event_BTN_REGISTRARActionPerformed

    private void BTN_AGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AGREGARActionPerformed
        // TODO add your handling code here:
        pestañas.setSelectedIndex(1);
    }//GEN-LAST:event_BTN_AGREGARActionPerformed

    private void BTN_SELECCIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SELECCIONARActionPerformed
    String tipo = TIPOOBRA.getSelectedItem().toString().toUpperCase();
        switch(tipo) {
            case "PINTURA":
                Menu_Obras.setSelectedIndex(0);  
                break;   
            case "ESCULTURA":
                Menu_Obras.setSelectedIndex(1);
                break;
            case "CERAMICA":
                Menu_Obras.setSelectedIndex(2);
                break;
            case "DIBUJO":
                Menu_Obras.setSelectedIndex(3);
                break;

            }
    }//GEN-LAST:event_BTN_SELECCIONARActionPerformed

    private void INGRESO_TIPLAPIZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESO_TIPLAPIZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INGRESO_TIPLAPIZActionPerformed

    private void INGRESO_TIPPAPELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESO_TIPPAPELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INGRESO_TIPPAPELActionPerformed
    private void limpiarCampos() {
    INGRESO_AUTOR.setText("");
    INGRESO_PRECIOBASE.setText("");
    INGRESO_ESTADO.setText("");
    INGRESO_DIMPINTURA.setText("");
    INGRESO_TECNICAPIN.setText("");
}
    private void BTN_AGREGARCERAMICAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AGREGARCERAMICAActionPerformed
        String tipo = TIPOOBRA.getSelectedItem().toString().toUpperCase();
        if("CERAMICA".equals(tipo)) {
            try {
            correo = v1.correo;
            autor = INGRESO_AUTOR.getText().trim();
            estado = INGRESO_ESTADO.getText().trim();
            preciobase = Integer.parseInt(INGRESO_PRECIOBASE.getText().trim());
            material = AGREGAR_MATERIALCERAMICA.getText().trim();
            
            preciobase = Integer.parseInt(INGRESO_PRECIOBASE.getText().trim());
            
            if(preciobase <= 0) {
                JOptionPane.showMessageDialog(this, "El precio debe ser mayor a cero", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
                detallesObra = "Cerámica - Tipo: " + tipo + ", Material: " + material;
                archiObra.adicionar(correo,autor,preciobase,estado,detallesObra);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(v3.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(v3.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            DefaultTableModel modelo = (DefaultTableModel) TABLA_REGISTROS.getModel();
            
            Object[] fila = {correo, autor, preciobase, estado, detallesObra};
            modelo.addRow(fila);
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Obra agregada exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BTN_AGREGARCERAMICAActionPerformed

    private void BTN_AGREGARPINTURAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AGREGARPINTURAActionPerformed
         String tipo = TIPOOBRA.getSelectedItem().toString().toUpperCase();
    
    if("PINTURA".equals(tipo)){
        try {
            correo = v1.correo;
            autor = INGRESO_AUTOR.getText().trim();
            estado = INGRESO_ESTADO.getText().trim();
            tecnica = INGRESO_TECNICAPIN.getText().trim();
            preciobase = Integer.parseInt(INGRESO_PRECIOBASE.getText().trim());
            dimension = Integer.parseInt(INGRESO_DIMPINTURA.getText().trim());

            if(preciobase <= 0 || dimension <= 0) {
                JOptionPane.showMessageDialog(this, "Precio y dimensión deben ser mayores a cero", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
                detallesObra = "Pintura - Técnica: " + tecnica + ", Dimensión: " + dimension + " cm";
                 archiObra.adicionar(correo,autor,preciobase,estado,detallesObra);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(v3.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IOException ex) {
                 Logger.getLogger(v3.class.getName()).log(Level.SEVERE, null, ex);
             }
            
            DefaultTableModel modelo = (DefaultTableModel) TABLA_REGISTROS.getModel();
            
            Object[] fila = {correo, autor, preciobase, estado, detallesObra};
            modelo.addRow(fila);

            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Obra agregada exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }   
      
    }//GEN-LAST:event_BTN_AGREGARPINTURAActionPerformed

    private void BTNAGREGAR_DIBUJOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAGREGAR_DIBUJOActionPerformed
         String tipo = TIPOOBRA.getSelectedItem().toString().toUpperCase();
        if("DIBUJO".equals(tipo)) {
            try {
            correo = v1.correo;
            autor = INGRESO_AUTOR.getText().trim();
            estado = INGRESO_ESTADO.getText().trim();
            tipoLapiz = INGRESO_TIPLAPIZ.getText().trim();
            tipoPapel = INGRESO_TIPPAPEL.getText().trim();
            
            preciobase = Integer.parseInt(INGRESO_PRECIOBASE.getText().trim());
            if(preciobase <= 0) {
                JOptionPane.showMessageDialog(this, "El precio debe ser mayor a cero", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
             detallesObra = "Dibujo - Lápiz: " + tipoLapiz + ", Papel: " + tipoPapel;
                 archiObra.adicionar(correo,autor,preciobase,estado,detallesObra);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(v3.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IOException ex) {
                 Logger.getLogger(v3.class.getName()).log(Level.SEVERE, null, ex);
             }
            DefaultTableModel modelo = (DefaultTableModel) TABLA_REGISTROS.getModel();
            
            Object[] fila = {correo, autor, preciobase, estado, detallesObra};
            modelo.addRow(fila);
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Obra agregada exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BTNAGREGAR_DIBUJOActionPerformed

    private void BTNAGREGAR_ESCULTURAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAGREGAR_ESCULTURAActionPerformed
         String tipo = TIPOOBRA.getSelectedItem().toString().toUpperCase();
        if("ESCULTURA".equals(tipo)) {
             try {
            correo = v1.correo;
            autor = INGRESO_AUTOR.getText().trim();
            estado = INGRESO_ESTADO.getText().trim();
            material = INGRESO_MATERIAL.getText().trim();
            
            preciobase = Integer.parseInt(INGRESO_PRECIOBASE.getText().trim());
            peso = Integer.parseInt(INGRESO_PESO.getText().trim());
            materialE = INGRESO_MATERIAL.getText().trim();
            if(preciobase <= 0 || peso <= 0) {
                JOptionPane.showMessageDialog(this, "Precio y peso deben ser mayores a cero", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
                 detallesObra = "Escultura - Material: " + material + ", Peso: " + peso + " kg";
                 archiObra.adicionar(correo,autor,preciobase,estado,detallesObra);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(v3.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IOException ex) {
                 Logger.getLogger(v3.class.getName()).log(Level.SEVERE, null, ex);
             }
            DefaultTableModel modelo = (DefaultTableModel) TABLA_REGISTROS.getModel();
            
            Object[] fila = {correo, autor, preciobase, estado, detallesObra};
            modelo.addRow(fila);
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Obra agregada exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_BTNAGREGAR_ESCULTURAActionPerformed

    private void INGRESO_PRECIOBASEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESO_PRECIOBASEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INGRESO_PRECIOBASEActionPerformed

    private void BTN_BUSCAR_EXPOSITORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BUSCAR_EXPOSITORActionPerformed
        // TODO add your handling code here:
        pestañas.setSelectedIndex(2);
    }//GEN-LAST:event_BTN_BUSCAR_EXPOSITORActionPerformed

    private void BTN_BUSCAR_EXPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BUSCAR_EXPActionPerformed
        // TODO add your handling code here:
        correo = CORREO_EXPOSITOR.getText().trim();
    
    if (correo.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Por favor ingrese un correo", 
            "Campo vacío", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        DefaultTableModel model = (DefaultTableModel) TABLA_BUSCAR.getModel();
        model.setRowCount(0); // Limpia la tabla antes de buscar
        
        // Contador para obras encontradas
        AtomicInteger contador = new AtomicInteger(0);
        
        archiObra.buscarObra(correo, obra -> {
            // Añade cada obra a la tabla
            model.addRow(new Object[]{
                obra.getCorreo(),
                obra.getAutor(),
                obra.getPrecioBase(),
                obra.getEstadoCompra(),
                obra.getDetalle()
            });
            contador.incrementAndGet();
        });
        
        // Muestra feedback al usuario
        if (contador.get() == 0) {
            JOptionPane.showMessageDialog(this,
                "No se encontraron obras para el correo: " + correo,
                "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                "Se encontraron " + contador.get() + " obra(s)",
                "Resultados", JOptionPane.INFORMATION_MESSAGE);
        }
        
    } catch (IOException | ClassNotFoundException e) {
        JOptionPane.showMessageDialog(this,
            "Error al acceder a los datos: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_BTN_BUSCAR_EXPActionPerformed

    private void CORREO_EXPOSITORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CORREO_EXPOSITORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CORREO_EXPOSITORActionPerformed

    private void TIPO_OBRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIPO_OBRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIPO_OBRAActionPerformed

    private void BTN_BUSCAR_POR_TIPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BUSCAR_POR_TIPOActionPerformed
        // TODO add your handling code here:
        String tipoBuscado = TIPO_OBRA.getSelectedItem().toString(); 
    
    try {
        DefaultTableModel model = (DefaultTableModel) TABLA_BUSCAR_POR_TIPO.getModel();
        model.setRowCount(0);
        
        archiObra.buscarPorTipo(tipoBuscado, obra -> {
            model.addRow(new Object[]{
                obra.getCorreo(),
                obra.getAutor(),
                obra.getPrecioBase(),
                obra.getEstadoCompra(),
                obra.getDetalle() // Aquí sigue mostrando el detalle completo
            });
        });
        
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                "No se encontraron obras del tipo: " + tipoBuscado,
                "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error al buscar: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BTN_BUSCAR_POR_TIPOActionPerformed

    private void BTN_BUSCAR_POR_TIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BUSCAR_POR_TIPActionPerformed
        // TODO add your handling code here:
        pestañas.setSelectedIndex(3);
    }//GEN-LAST:event_BTN_BUSCAR_POR_TIPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new v3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AGREGAR_MATERIALCERAMICA;
    private javax.swing.JTextField AGREGAR_TIPOCERAMICA;
    private javax.swing.JButton BTNAGREGAR_DIBUJO;
    private javax.swing.JButton BTNAGREGAR_ESCULTURA;
    private javax.swing.JButton BTN_AGREGAR;
    private javax.swing.JButton BTN_AGREGARCERAMICA;
    private javax.swing.JToggleButton BTN_AGREGARPINTURA;
    private javax.swing.JButton BTN_BUSCAR_EXP;
    private javax.swing.JButton BTN_BUSCAR_EXPOSITOR;
    private javax.swing.JButton BTN_BUSCAR_POR_TIP;
    private javax.swing.JButton BTN_BUSCAR_POR_TIPO;
    private javax.swing.JButton BTN_REGISTRAR;
    private javax.swing.JButton BTN_SELECCIONAR;
    private javax.swing.JTextField CORREO_EXPOSITOR;
    private javax.swing.JTextField INGRESO_AUTOR;
    private javax.swing.JTextField INGRESO_DIMPINTURA;
    private javax.swing.JTextField INGRESO_ESTADO;
    private javax.swing.JTextField INGRESO_MATERIAL;
    private javax.swing.JTextField INGRESO_PESO;
    private javax.swing.JTextField INGRESO_PRECIOBASE;
    private javax.swing.JTextField INGRESO_TECNICAPIN;
    private javax.swing.JTextField INGRESO_TIPLAPIZ;
    private javax.swing.JTextField INGRESO_TIPPAPEL;
    private javax.swing.JTabbedPane Menu_Obras;
    private javax.swing.JPanel PNL_AGREGAR;
    private javax.swing.JPanel PNL_BUSCAR;
    private javax.swing.JPanel PNL_BUSCAR_TIPO;
    private javax.swing.JPanel PNL_CERAMICA;
    private javax.swing.JPanel PNL_DIBUJO;
    private javax.swing.JPanel PNL_ESCULTURA;
    private javax.swing.JPanel PNL_PINTURA;
    private javax.swing.JPanel PNL_REGISTRAR;
    private javax.swing.JTable TABLA_BUSCAR;
    private javax.swing.JTable TABLA_BUSCAR_POR_TIPO;
    private javax.swing.JTable TABLA_REGISTROS;
    private javax.swing.JComboBox<String> TIPOOBRA;
    private javax.swing.JComboBox<String> TIPO_OBRA;
    private javax.swing.JButton btn_Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane pestañas;
    // End of variables declaration//GEN-END:variables
}
